server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "https://veridocx-frontend.netlify.app"   # ✅ CHANGE THIS
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: user-service
          uri: https://veridocx-backend.onrender.com   # ✅ FIXED
          predicates:
            - Path=/api/auth/**,/api/v1/users/**

        - id: document-service
          uri: https://veridocx-documentservice.onrender.com
          predicates:
            - Path=/api/v1/documents/**

        - id: verification-service
          uri: https://veridocx-verificationservice.onrender.com
          predicates:
            - Path=/api/v1/verify/**

        - id: audit-service
          uri: https://veridocx-auditservices.onrender.com
          predicates:
            - Path=/api/v1/audit/**
